---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - watcher.operators.kcddhaka.org
  resources:
  - deploymentwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.operators.kcddhaka.org
  resources:
  - deploymentwatchers/finalizers
  verbs:
  - update
- apiGroups:
  - watcher.operators.kcddhaka.org
  resources:
  - deploymentwatchers/status
  verbs:
  - get
  - patch
  - update
